apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-api
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
  selector:
    app: api
